# Clinical & data priors for the diabetes regression pilot
# Note: features from sklearn.diabetes are standardized (z-score).
# This file defines how to derive limits and tolerances from the data itself,
# without assuming absolute clinical ranges.

meta:
  dataset: "sklearn.diabetes"
  target: "target"          # continuous measure of disease progression
  standardization: "zscore" # indicates that X are normalized in origin

bounds_strategy:
  # Default strategy to set feature bounds: use dataset percentiles
  from_data_percentiles:
    low: 1
    high: 99

tolerances:
  # τ — empirical threshold for Additivity (operationalized as Completeness)
  additivity_abs_tau: 5.0           # units of the target (adjust if scale changes)
  # ε — perturbation magnitude for Consistency (observed as Stability)
  consistency_perturbation:
    scheme: "relative"              # "absolute" or "relative"
    epsilon: 0.02                   # 2% of feature std deviation

immutables:
  # Variables that CANNOT change in counterfactuals
  - "sex"
  - "age"

actionable:
  # Variables that CAN change (e.g., lifestyle proxies)
  # Keep all except immutables; further restrict if clinically needed.
  include:
    - "bmi"
    - "bp"
    - "s1"
    - "s2"
    - "s3"
    - "s4"
    - "s5"
    - "s6"

costs:
  # Relative cost of changing each feature (for DiCE/optimization)
  # 1.0 = base cost; >1.0 harder to change; <1.0 easier
  # Adjust with clinical or social rationale (e.g., changing BMI is costly → 2.0)
  default: 1.0
  per_feature:
    bmi: 2.0
    bp: 1.5
    s1: 1.0
    s2: 1.0
    s3: 1.0
    s4: 1.0
    s5: 1.0
    s6: 1.0

profiles:
  # Two user profiles to align technical (clinician) and social (patient) trust
  clinician:
    explanation_focus: ["fidelity", "additivity", "consistency", "plausibility"]
    acceptance_criteria:
      additivity_min_pct: 0.95
      consistency_cosine_median_min: 0.90
      plausible_cf_min_pct: 0.80
  patient:
    explanation_focus: ["actionability", "clarity", "diversity"]
    # Limit number and magnitude of suggested changes for realistic proposals
    max_changes: 3
    max_step_relative: 0.5   # fraction of feature std deviation
    present_top_k_features: 3
